In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
import tensorflow as tf

In [6]:
### sentences
sent = [
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good",
]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
## Define the vocabulary size
voc_size = 10000

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[8561, 1702, 9905, 6810],
 [8561, 1702, 9905, 4870],
 [8561, 856, 9905, 7235],
 [2460, 8476, 2966, 9749, 9128],
 [2460, 8476, 2966, 9749, 5903],
 [7488, 8561, 7971, 9905, 9696],
 [6497, 3815, 2842, 9749]]

In [11]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding

# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8561 1702 9905 6810]
 [   0    0    0    0 8561 1702 9905 4870]
 [   0    0    0    0 8561  856 9905 7235]
 [   0    0    0 2460 8476 2966 9749 9128]
 [   0    0    0 2460 8476 2966 9749 5903]
 [   0    0    0 7488 8561 7971 9905 9696]
 [   0    0    0    0 6497 3815 2842 9749]]


In [14]:
## feature representation
dim = 10

In [15]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile("adam", "mse")

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 85ms/step


array([[[-3.36498618e-02,  4.31101955e-02,  1.92896612e-02,
          1.01109967e-02,  9.25578922e-03, -1.37839466e-03,
          1.15618855e-03,  3.80949490e-02,  1.26740970e-02,
         -4.85030673e-02],
        [-3.36498618e-02,  4.31101955e-02,  1.92896612e-02,
          1.01109967e-02,  9.25578922e-03, -1.37839466e-03,
          1.15618855e-03,  3.80949490e-02,  1.26740970e-02,
         -4.85030673e-02],
        [-3.36498618e-02,  4.31101955e-02,  1.92896612e-02,
          1.01109967e-02,  9.25578922e-03, -1.37839466e-03,
          1.15618855e-03,  3.80949490e-02,  1.26740970e-02,
         -4.85030673e-02],
        [-3.36498618e-02,  4.31101955e-02,  1.92896612e-02,
          1.01109967e-02,  9.25578922e-03, -1.37839466e-03,
          1.15618855e-03,  3.80949490e-02,  1.26740970e-02,
         -4.85030673e-02],
        [-4.58574556e-02,  1.61473826e-03,  1.15227923e-02,
          4.57850806e-02, -2.45442037e-02, -2.58542597e-04,
         -3.18683386e-02, -4.55472954e-02, -1.802865

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 8561, 1702, 9905, 6810])

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 54ms/step


array([[-0.03364986,  0.0431102 ,  0.01928966,  0.010111  ,  0.00925579,
        -0.00137839,  0.00115619,  0.03809495,  0.0126741 , -0.04850307],
       [-0.03364986,  0.0431102 ,  0.01928966,  0.010111  ,  0.00925579,
        -0.00137839,  0.00115619,  0.03809495,  0.0126741 , -0.04850307],
       [-0.03364986,  0.0431102 ,  0.01928966,  0.010111  ,  0.00925579,
        -0.00137839,  0.00115619,  0.03809495,  0.0126741 , -0.04850307],
       [-0.03364986,  0.0431102 ,  0.01928966,  0.010111  ,  0.00925579,
        -0.00137839,  0.00115619,  0.03809495,  0.0126741 , -0.04850307],
       [-0.04585746,  0.00161474,  0.01152279,  0.04578508, -0.0245442 ,
        -0.00025854, -0.03186834, -0.0455473 , -0.01802865,  0.01953251],
       [-0.00641833,  0.02705406,  0.0153389 , -0.00958562,  0.02580378,
         0.00402664,  0.04339627, -0.01996417,  0.01052292, -0.03251972],
       [-0.02767779, -0.03176668,  0.03031839, -0.03811678,  0.03403967,
        -0.0372122 , -0.03138648, -0.02315329

In [20]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices("GPU")))

Num GPUs Available:  0


In [21]:
import tensorflow as tf

print(tf.config.list_physical_devices("GPU"))

[]
